USE bd_aula_node;

-- Relacionamento: PERFIL_GESTOR -> USUARIO
ALTER TABLE PERFIL_GESTOR
    ADD CONSTRAINT fk_gestor_usuario 
    FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- Relacionamentos: MEMBRO_EQUIPE -> EQUIPE_CAMPO e USUARIO
ALTER TABLE MEMBRO_EQUIPE
    ADD CONSTRAINT fk_membro_equipe 
    FOREIGN KEY (id_equipe) REFERENCES EQUIPE_CAMPO(id_equipe)
    ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT fk_membro_usuario 
    FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- Relacionamentos: OCORRENCIA -> USUARIO (cidadão) e CATEGORIA_OCORRENCIA
ALTER TABLE OCORRENCIA
    ADD CONSTRAINT fk_ocorrencia_cidadao 
    FOREIGN KEY (id_cidadao) REFERENCES USUARIO(id_usuario)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT fk_ocorrencia_categoria 
    FOREIGN KEY (id_categoria) REFERENCES CATEGORIA_OCORRENCIA(id_categoria)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- Relacionamento: ANEXO_OCORRENCIA -> OCORRENCIA
ALTER TABLE ANEXO_OCORRENCIA
    ADD CONSTRAINT fk_anexo_ocorrencia 
    FOREIGN KEY (id_ocorrencia) REFERENCES OCORRENCIA(id_ocorrencia)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- Relacionamentos: INTERACAO_MENSAGEM -> OCORRENCIA e USUARIO (remetente)
ALTER TABLE INTERACAO_MENSAGEM
    ADD CONSTRAINT fk_interacao_ocorrencia 
    FOREIGN KEY (id_ocorrencia) REFERENCES OCORRENCIA(id_ocorrencia)
    ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT fk_interacao_remetente 
    FOREIGN KEY (id_remetente) REFERENCES USUARIO(id_usuario)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- Relacionamentos: ORDEM_SERVICO -> OCORRENCIA, PERFIL_GESTOR e EQUIPE_CAMPO
ALTER TABLE ORDEM_SERVICO
    ADD CONSTRAINT fk_os_ocorrencia 
    FOREIGN KEY (id_ocorrencia) REFERENCES OCORRENCIA(id_ocorrencia)
    ON DELETE CASCADE ON UPDATE CASCADE,
    ADD CONSTRAINT fk_os_gestor 
    FOREIGN KEY (id_gestor) REFERENCES PERFIL_GESTOR(id_gestor)
    ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT fk_os_equipe 
    FOREIGN KEY (id_equipe) REFERENCES EQUIPE_CAMPO(id_equipe)
    ON DELETE RESTRICT ON UPDATE CASCADE;

-- Relacionamento: EVIDENCIA_SERVICO -> ORDEM_SERVICO
ALTER TABLE EVIDENCIA_SERVICO
    ADD CONSTRAINT fk_evidencia_os 
    FOREIGN KEY (id_os) REFERENCES ORDEM_SERVICO(id_os)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- Relacionamento: AVALIACAO_ATENDIMENTO -> OCORRENCIA
ALTER TABLE AVALIACAO_ATENDIMENTO
    ADD CONSTRAINT fk_avaliacao_ocorrencia 
    FOREIGN KEY (id_ocorrencia) REFERENCES OCORRENCIA(id_ocorrencia)
    ON DELETE CASCADE ON UPDATE CASCADE;